[[rewritepath-gatewayfilter-factory]]
= `RewritePath` `GatewayFilter` Factory

The `RewritePath` `GatewayFilter` factory takes a path `regexp` parameter and a `replacement` parameter.
This uses Java regular expressions for a flexible way to rewrite the request path.
The following listing configures a `RewritePath` `GatewayFilter`:

.application.yml
[source,yaml]
----
spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
          - id: rewritepath_route
            uri: https://example.org
            predicates:
            - Path=/red/**
            filters:
            - RewritePath=/red/?(?<segment>.*), /$\{segment}
----

For a request path of `/red/blue`, this sets the path to `/blue` before making the downstream request. Note that the `$` should be replaced with `$\` because of the YAML specification.

NOTE: If the request has a context path (for example, when `spring.webflux.base-path` is set or a forwarded prefix applies), add the xref:spring-cloud-gateway-server-webflux/gatewayfilter-factories/stripcontextpath-factory.adoc[`StripContextPath` filter] before this filter to remove the context path first; otherwise, mutating the path can fail with an invalid context path error or retain an unintended context-path prefix.

