[[setpath-gatewayfilter-factory]]
= `SetPath` `GatewayFilter` Factory

The `SetPath` `GatewayFilter` factory takes a path `template` parameter.
It offers a simple way to manipulate the request path by allowing templated segments of the path.
This uses the URI templates from Spring Framework.
Multiple matching segments are allowed.
The following example configures a `SetPath` `GatewayFilter`:

.application.yml
[source,yaml]
----
spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
          - id: setpath_route
            uri: https://example.org
            predicates:
            - Path=/red/{segment}
            filters:
            - SetPath=/{segment}
----

For a request path of `/red/blue`, this sets the path to `/blue` before making the downstream request.

NOTE: If the request has a context path (for example, when `spring.webflux.base-path` is set or a forwarded prefix applies), add the xref:spring-cloud-gateway-server-webflux/gatewayfilter-factories/stripcontextpath-factory.adoc[`StripContextPath` filter] before this filter to remove the context path first; otherwise, mutating the path fails with an invalid context path error.

