[[stripprefix-gatewayfilter-factory]]
= `StripPrefix` `GatewayFilter` Factory

The `StripPrefix` `GatewayFilter` factory takes one parameter, `parts`.
The `parts` parameter indicates the number of parts in the path to strip from the request before sending it downstream.
The following listing configures a `StripPrefix` `GatewayFilter`:

.application.yml
[source,yaml]
----
spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
          - id: nameRoot
            uri: https://nameservice
            predicates:
            - Path=/name/**
            filters:
            - StripPrefix=2
----

When a request is made through the gateway to `/name/blue/red`, the request made to `nameservice` looks like `https://nameservice/red`.

NOTE: If the request has a context path (for example, when `spring.webflux.base-path` is set or a forwarded prefix applies), add the xref:spring-cloud-gateway-server-webflux/gatewayfilter-factories/stripcontextpath-factory.adoc[`StripContextPath` filter] before this filter to remove the context path first; otherwise, mutating the path fails with an invalid context path error.

