[[local-cache-response-filter]]
= `LocalResponseCache` Filter

This filter allows caching the response body and headers to follow these rules:

* It can only cache bodiless GET requests.
* It caches the response only for one of the following status codes: HTTP 200 (OK), HTTP 206 (Partial Content), or HTTP 301 (Moved Permanently).
* Response data is not cached if `Cache-Control` header does not allow it (`no-store` present in the request or `no-store` or `private` present in the response).
* Response data is not cached if the response `Vary` header is `*`.
* Response data is not cached if the response has a streaming media type (see `spring.cloud.gateway.server.webmvc.streaming-media-types`).
* If a new request is performed with `no-cache` value in `Cache-Control` header, the request is forwarded to the upstream and the existing cache entry is kept.

This filter configures the local response cache per route.

It accepts the first parameter to override the time to expire a cache entry (expressed in `s` for seconds, `m` for minutes, and `h` for hours) and a second parameter to set the maximum size of the cache to evict entries for this route (`KB`, `MB`, or `GB`).
Both parameters are optional: if the time to live is not set, it defaults to 5 minutes; if the maximum size is not set, the cache is not size-bounded.

The following listing shows how to add the local response cache filter:

.application.yml
[source,yaml]
----
spring:
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: resource
              uri: http://localhost:9000
              predicates:
              - Path=/resource
              filters:
              - LocalResponseCache=30m,500MB
----

.GatewaySampleApplication.java
[source,java]
----
import static org.springframework.cloud.gateway.server.mvc.filter.BeforeFilterFunctions.uri;
import static org.springframework.cloud.gateway.server.mvc.filter.ResponseCacheFilterFunctions.localResponseCache;
import static org.springframework.cloud.gateway.server.mvc.handler.GatewayRouterFunctions.route;
import static org.springframework.cloud.gateway.server.mvc.handler.HandlerFunctions.http;

@Configuration
class RouteConfiguration {

    @Bean
    public RouterFunction<ServerResponse> gatewayRouterFunctionsCache() {
        return route("resource")
            .GET("/resource", http())
            .before(uri("http://localhost:9000"))
            .filter(localResponseCache(Duration.ofMinutes(30), DataSize.parse("500MB")))
            .build();
    }
}
----

NOTE: This filter also automatically calculates the `max-age` value in the HTTP `Cache-Control` header.
If `max-age` is not present on the original response, the value is set to the number of seconds set in the `timeToLive` configuration parameter.
In consecutive calls, this value is recalculated with the number of seconds left until the response expires.

NOTE: To enable this feature, add `com.github.ben-manes.caffeine:caffeine` as a project dependency.
