:github-tag: master
:github-repo: spring-cloud-incubator/spring-cloud-gateway
:github-raw: http://raw.github.com/{github-repo}/{github-tag}
:github-code: http://github.com/{github-repo}/tree/{github-tag}
:all: {asterisk}{asterisk}
:nofooter:
:imagesdir: ./images
= Spring Cloud Gateway

*{spring-cloud-version}*

include::intro.adoc[]

[[gateway-starter]]
== How to Include Spring Cloud Gateway

To include Spring Cloud Gateway in your project use the starter with group `org.springframework.cloud`
and artifact id `spring-cloud-starter-gateway`. See the http://projects.spring.io/spring-cloud/[Spring Cloud Project page]
for details on setting up your build system with the current Spring Cloud Release Train.

Include the `@EnableGateway` annotation on any `@Configuration` class to enable Spring Cloud Gateway.

== Glossary

TODO: document the meaning of terms to follow, like Route, Predicate and Filter

[[gateway-how-it-works]]
== How It Works

TODO: give an overview of how the gateway works with maybe a ascii diagram

[[gateway-request-predicates-factories]]
== Request Predicate Factories

Spring Cloud Gateway matches routes as part of the Spring WebFlux `HandlerMapping` infrastructure. Spring Cloud Gateway includes many built-in Request Predicate Factorys. All of these predicates match on different attributes of the HTTP request. Multiple Request Predicate Factorys can be combined and are combined via logical `and`.

=== After Request Predicate Factory
TODO: document After Request Predicate Factory

=== Before Request Predicate Factory
TODO: document Before Request Predicate Factory

=== Between Request Predicate Factory
TODO: document Between Request Predicate Factory

=== Cookie Request Predicate Factory
The Cookie Request Predicate Factory takes two parameters, the cookie name and a regular expression. This predicate matches cookies that have the given name and the value matches the regular expression.

.application.yml
[source,yaml]
----
spring:
  cloud:
    gateway:
      routes:
      # =====================================
      - id: cookie_route
        uri: http://example.org
        predicates:
        - Cookie=chocolate, ch.p
----

This route matches the request has a cookie named `chocolate` who's value matches the `ch.p` regular expression.

=== Header Request Predicate Factory
The Header Request Predicate Factory takes two parameters, the header name and a regular expression. This predicate matches with a header that has the given name and the value matches the regular expression.

.application.yml
[source,yaml]
----
spring:
  cloud:
    gateway:
      routes:
      # =====================================
      - id: header_route
        uri: http://example.org
        predicates:
        - Header=X-Request-Id, \d+
----

This route matches if the request has a header named `X-Request-Id` whos value matches the `\d+` regular expression (has a value of one or more digits).

=== Host Request Predicate Factory
The Host Request Predicate Factory takes one parameter: the host name pattern. The pattern is an Ant style pattern with `.` as the separator. This predicates matches the `Host` header that matches the pattern.

.application.yml
[source,yaml]
----
spring:
  cloud:
    gateway:
      routes:
      # =====================================
      - id: host_route
        uri: http://example.org
        predicates:
        - Host=**.somehost.org
----

This route would match if the request has a `Host` header has the value `www.somehost.org` or `beta.somehost.org`.


=== Method Request Predicate Factory
The Method Request Predicate Factory takes one parameter: the HTTP method to match.

.application.yml
[source,yaml]
----
spring:
  cloud:
    gateway:
      routes:
      # =====================================
      - id: method_route
        uri: http://example.org
        predicates:
        - Method=GET
----

This route would match if the request method was a `GET`.

=== Path Request Predicate Factory
The Path Request Predicate Factory takes one parameter: a Spring `PathMatcher` pattern.

.application.yml
[source,yaml]
----
spring:
  cloud:
    gateway:
      routes:
      # =====================================
      - id: host_route
        uri: http://example.org
        predicates:
        - Path=/foo/{segment}
----

This route would match if the request path was, for example: `/foo/1` or `/foo/bar`.

This predicate extracts the URI template variables (like `segment` defined in the example above) as a map of names and values and places it in the `ServerWebExchange.getAttributes()` with a key defined in `PathRoutePredicate.URL_PREDICATE_VARS_ATTR`. Those values are then available for use by <<gateway-route-filters,Route Filters>>

=== Query Request Predicate Factory
TODO: document Query Request Predicate Factory

=== RemoteAddr Request Predicate Factory
TODO: document RemoteAddr Request Predicate Factory

[[gateway-route-filters]]
== Route Filters

Route filters allow the modification of the incoming HTTP request or outgoing HTTP response in some manner. Route filters are scoped to a particular route. Spring Cloud Gateway includes many built-in Route Filters.

=== AddRequestHeader Route Filter
TODO: document AddRequestHeader Route Filter

=== AddRequestParameter Route Filter
TODO: document AddRequestParameter Route Filter

=== AddResponseHeader Route Filter
TODO: document AddResponseHeader Route Filter

=== Hystrix Route Filter
TODO: document Hystrix Route Filter

=== PrefixPath Route Filter
TODO: document PrefixPath Route Filter

=== RedirectTo Route Filter
TODO: document RedirectTo Route Filter

=== RemoveNonProxyHeaders Route Filter
TODO: document RemoveNonProxyHeaders Route Filter

=== RemoveRequestHeader Route Filter
TODO: document RemoveRequestHeader Route Filter

=== RemoveResponseHeader Route Filter
TODO: document RemoveResponseHeader Route Filter

=== RewritePath Route Filter
TODO: document RewritePath Route Filter

=== SecureHeaders Route Filter
TODO: document SecureHeaders Route Filter

=== SetPath Route Filter
TODO: document SetPath Route Filter

=== SetResponseHeader Route Filter
TODO: document SetResponseHeader Route Filter

=== SetStatus Route Filter
TODO: document SetStatus Route Filter

== Global Filters

TODO: document Global Filters

== Configuration

TODO: document configuration via Spring Boot external properties

== Actuator API

TODO: document the `/gateway` actuator endpoint

== Developer Guide

TODO: overview of writing custom integrations

=== Writing Custom Request Predicate Factorys

TODO: document writing Custom Request Predicate Factorys

=== Writing Custom Route Filters

TODO: document writing Custom Route Filters

=== Writing Custom Global Filters

TODO: document writing Custom Global Filters

=== Writing Custom Route Locators and Writers

TODO: document writing Custom Route Locators and Writers
